### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by somebabyTina** [miguki/AppTaskReload#1]
After importing the extension to qlik sense.
It cannot be used from hub.
Hence I go to dev-hub, trying to open the extension but popup attached error.
wdfolder.wdl file misssing.

![An_error_occurred](https://user-images.githubusercontent.com/61138875/74642666-5e82a100-51ae-11ea-8e9b-89b6456be474.jpg)

Do you know what's wrong ?

**Comment by miguki** [comment]
Hi, I have added wbfolder.wbl file to current release. Download it, delete old and import new zip. If you encounter any more problems please try to use some other editor than Dev-Hub as it usually doesn't work anyway
