### ISSUE TITLE
Opening sheet crashes

### ISSUE THREAD

**Issue by paulverkooijen** [miguki/AppTaskReload#2]
Hi Miguki,

The extension crashes when using a Prefix virtual proxy ? Using Feb 2020 Have an additional forms authentication virtual proxy
![image](https://user-images.githubusercontent.com/23397054/77626482-ba76dd00-6f45-11ea-871b-657002451ace.png)

**Comment by miguki** [comment]
Hi,

Is it Forms type of auth? I will check that and get back to you

![image](https://user-images.githubusercontent.com/29373292/77705567-475e7c80-6fc0-11ea-809c-ecdfe067a755.png)

**Comment by miguki** [comment]
There was a problem with virtual proxy with prefix. I added support for such configuration. Please try version 3.1.1

**Comment by paulverkooijen** [comment]
Thnx it works
